#server:
#  port: 9004
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost
#
#spring:
#  application:
#    name: CLOUD-GATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id : USER-SERVICE
#          url: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#        - id : DEPARTMENT-SERVICE
#          url: lb://DEPARTMENT-SERVICE
#          predicates:
#            - Path=/department/**
#
